### ISSUE TITLE
关于本项目

### ISSUE THREAD

**Issue by kinegratii** [kinegratii/django-echarts#1]
在网页上显示Echarts图表这个问题领域中，该项目与pyecharts的关系，可以和 [django-import-export](https://django-import-export.readthedocs.io/) 与 [tablib](http://docs.python-tablib.org/en/latest/)  关系相类似，它们是实现xlsx/xls/csv/json/yaml 文件数据导入导出功能的非常优秀的开源项目。

django-echarts实现了一个通用的架构，在视图类中构建符合功能需求的 `pyecharts.base.Base` 对象，将其 `_option` 值（目前未有public的API），直接返回给前端，最后通过
 `echartsInstance.setOptions(options)` 的前端代码完成渲染。

项目着重于后端开发，因为如果需要更加复杂细致的定制需求，显然将这些放在前端 Echarts 是为一个更好的选择。

项目主要开发内容：

- 与Django数据查询的整合
- 与其他功能的整合，尽可能不破坏原有结构
- 其他待定

**Comment by chfw** [comment]
毛遂自荐一下，能否考虑用[django-excel](http://django-excel.readthedocs.io/en/latest/)。我这库已经实现excel,django query数据读取，展现。另外，请移步看看我的一个待发展的库[pyexcel-echarts](https://github.com/pyexcel/pyexcel-echarts)。看kinegratti有什么想法，请拍砖。

**Comment by chenjiandongx** [comment]
@kinegratii 
如果你是想要 pyecharts 提供一个 options 属性返回 self._option 吗？

**Comment by kinegratii** [comment]
@chfw 目前也在思考数据构建模块这一层的设计实现问题，如有现成库实现那是最好的。我会认真研究整合的实现方式，有什么问题再请教。

**Comment by kinegratii** [comment]
@chenjiandongx 嗯，可以使用 `@porperty` 方式返回配置项或其他属性。

**Comment by chenjiandongx** [comment]
嗯 昨天已经为所有图提供了 options 属性了 会返回self._option
