### ISSUE TITLE
新手  求帮助文档~

### ISSUE THREAD

**Issue by sailf** [kinegratii/django-echarts#2]
求帮助文档~

**Comment by kinegratii** [comment]
@sailf 

1. 目前项目仅实现了通过js渲染方式的这一功能，文档在Readme.md的Basic Usage一节，示例可参考example代码。
2. 其他外围功能还在思考设计中，比如更好地支持Django模板渲染方式，这也是 [pyecharts](https://github.com/chenjiandongx/pyecharts) 目前所支持的方式（由于目标问题不同，没有提供更多的自定义操作）。
