### ISSUE TITLE
setup.py should have pyecharts in install_requires

### ISSUE THREAD

**Issue by chfw** [kinegratii/django-echarts#20]
https://github.com/kinegratii/django-echarts/blob/master/setup.py#L34

**Comment by chfw** [comment]
pyecharts>=0.3.x

**Comment by kinegratii** [comment]
1 *django-echarts* don't need *pyecharts* and *django* as its dependency library.
2 The command `pip install django-echarts` will not change automatically the installation of *pyecharts* and *django* .

**Comment by chfw** [comment]
with an empty environment, `pip install django-echarts` won't bring user pyecharts, unless they do it themselves.
