### ISSUE TITLE
Object of type 'Tooltip' is not JSON serializable 

### ISSUE THREAD

**Issue by weisong82** [kinegratii/django-echarts#24]
TypeError at /demo/options/simplePie/
Object of type 'Tooltip' is not JSON serializable

Django                    2.1                       <pip>
django-echarts            0.3.6                     <pip>
pyecharts                 0.5.6                     <pip>
pyecharts-javascripthon   0.0.6                     <pip>
pyecharts-jupyter-installer 0.0.3                     <pip>

**Comment by kinegratii** [comment]
Sorry,django-echarts is not supported pyecharts 0.5+ yet.
