### ISSUE TITLE
如何向模板中传递其他的参数

### ISSUE THREAD

**Issue by MK0820** [kinegratii/django-echarts#26]
现在遇到一种情况就是，我除了要向模板文件中传递图表对象之外，还有一些别的变量要传递过去，那么请问我应该怎么做呢。谢谢。
`class NamedChartsView(EChartsBackendView):`
`    ...` 
`     def get_echarts_instance(self, *args, **kwargs):` 
`         ....` 
`         line = Line()` 
`         something = 'something'` 
`         return line`
比如这里我想把` something` 也传递过去。

**Comment by NINGZHILIANG** [comment]
我输入 python manage.py runserver ，后一直报错
ImportError: cannot import name 'Bar' from 'pyecharts' (D:\app\Python-3.7.3\lib\site-packages\pyecharts\_
_init__.py)
请问是什么原因？

**Comment by SeepenL** [comment]
> 我输入 python manage.py runserver ，后一直报错
> ImportError: cannot import name 'Bar' from 'pyecharts' (D:\app\Python-3.7.3\lib\site-packages\pyecharts_
> _init__.py)
> 请问是什么原因？

是因为这个项目用的pyecharts版本太低了，目前版本为v1.x，其中所有的图表类都集成到pyecharts.charts中了，就是说from的应该是这个包。
但是就算头部更改了，程序只要调用图表api的地方也都需要改，因为新版本传参格式不一样了。这就很麻烦。
