### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by Winky678** [kinegratii/django-echarts#31]
![image](https://user-images.githubusercontent.com/41333749/159652280-20b62ec6-33e0-4c4e-aed9-6278a7a7c60e.png)
![image](https://user-images.githubusercontent.com/41333749/159652433-54e9a105-6c7e-40de-8dda-ed84e64a46ac.png)

**Comment by kinegratii** [comment]
## 临时解决方案：

1. 使用完整导入路径
正确使用方法
```python
from django_echarts.starter.sites import DJESite
```

错误使用方法
```python
from django_echarts.starter import DJESite
```

2. Hack源代码

报错的一行修改如下：
```
from .sites import DJESite, DJESiteBackendView
```

**Comment by Winky678** [comment]
大佬，这个框架，怎么把templates里面的html 加到 "基本信息"  下面呢
![image](https://user-images.githubusercontent.com/41333749/159881420-effa7a93-1470-4088-bd5e-da9a38579976.png)

**Comment by kinegratii** [comment]
@Winky678 
第一，视图必须采用 CBV形式，并继承 `DJESiteBackendView` 类。 参见 https://django-echarts.readthedocs.io/reference/api/ 。
第二，添加到导航栏，使用 `site_obj.add_left_link`。

**视图代码**
```python

class MyMapDataView(DJESiteBackendView):
    template_name = 'MAP.html'
    def dje_init_page_context(self, context, site: 'DJESite') -> Optional[str]:
        # 修改context，传入模板变量
        pass

item = LinkItem(text='我的地图', url=reverse_lazy('my_map'))
site_obj.add_right_link(item)

```


**urls.py模块**

```python
urlpatterns = [
    # ...
    path('mymap', MyMapDataView.as_view(), name='my_map'),
    #...
]

```

**Comment by Winky678** [comment]
感谢大佬解答，但是按照上面的方法直线之后，我的效果是这样的，有办法可以弄到箭头那个位置吗 ，哈哈哈
![image](https://user-images.githubusercontent.com/41333749/160320622-9c13d676-5474-4f6a-ada3-f2b93cb5496e.png)

**Comment by Winky678** [comment]
![image](https://user-images.githubusercontent.com/41333749/160341892-215cdcdb-474b-412d-91ed-8bf413dbc930.png)
大标题显示不出来

**Comment by Winky678** [comment]
大佬，看你的文档写得挺好，如果里面能加一下举例的代码就更好了，嘿嘿~ https://django-echarts.readthedocs.io/reference/api/#djesitebackendview_1

**Comment by kinegratii** [comment]
@Winky678 感谢支持！

可能是这个主题的配色和文字颜色相近，可以换个主题看看。

文档方面还在梳理完善之中，后续会推出专门的示例项目。
